[package]
name = "embassy-lpc55"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = "1.1.2"
embassy-hal-internal = {version = "0.1.0", path = "../embassy-hal-internal", features = ["cortex-m", "prio-bits-2"] }
lpc55-pac = "0.5.0"
