[package]
name = "embassy-lpc55"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = "1.1.2"
embassy-hal-internal = {version = "0.1.0", path = "../embassy-hal-internal", features = ["cortex-m", "prio-bits-2"] }
embassy-time-driver = { version = "0.1", path = "../embassy-time-driver"}
embassy-sync = { version = "0.6.0", path = "../embassy-sync" }
lpc55-hal = "0.3.0"
cortex-m-rt = "0.6.13"
atomic-polyfill = "1.0.1"
defmt = "0.3.8"

